### ISSUE TITLE
Make MultipleArbitrableTransaction to also work for payments in tokens ERC20

### ISSUE THREAD

**Issue by clesaege** [kleros/kleros-interaction#124] opened 2018-09-17 16:13 UTC
https://github.com/kleros/kleros-interaction/blob/master/contracts/standard/arbitration/MultipleArbitrableTransaction.sol

**Comment by ferittuncer** [comment] 2018-10-03 15:06
Is this duplicate of #111 ? @clesaege

**Closed** 2018-11-12 20:59 UTC
Labels: Priority: Medium, Status: Available, Type: Enhancement :sparkles:
